Update integration_tests.yml
Remove Native Merge test temporarily

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -80,10 +80,10 @@ jobs:
         run: |
           make prime-editor test print
 
-      - name: Run Native Merging
-        if: success() || failure()
-        run: |
-          make nhej_native_merge test print
+      # - name: Run Native Merging
+      #   if: success() || failure()
+      #   run: |
+      #     make nhej_native_merge test print
 
       - name: Run BAM Input
         if: success() || failure()
